ALTER TABLE documents
ADD COLUMN created TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
ADD COLUMN updated TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

CREATE TRIGGER trigger_update_updated
BEFORE UPDATE ON documents
FOR EACH ROW
EXECUTE FUNCTION update_updated();

