// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID      int32            `json:"id"`
	UserID  int32            `json:"user_id"`
	Content string           `json:"content"`
	Private pgtype.Bool      `json:"private"`
	Created pgtype.Timestamp `json:"created"`
	Updated pgtype.Timestamp `json:"updated"`
}

type User struct {
	ID       int32       `json:"id"`
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	Password string      `json:"password"`
}
