// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (user_id, content, private)
VALUES ($1, $2, $3)
RETURNING id, user_id, content, private, created, updated
`

type CreateDocumentParams struct {
	UserID  int32       `json:"user_id"`
	Content string      `json:"content"`
	Private pgtype.Bool `json:"private"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.UserID, arg.Content, arg.Private)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Private,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password)
VALUES ($1, $2, $3)
RETURNING id, username, email, password
`

type CreateUserParams struct {
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	Password string      `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocuments = `-- name: GetDocuments :many
SELECT id, user_id, content, private, created, updated
FROM documents
ORDER BY updated DESC
LIMIT $1
`

func (q *Queries) GetDocuments(ctx context.Context, limit int64) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Private,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByUserID = `-- name: GetDocumentsByUserID :many
SELECT id, user_id, content, private, created, updated
FROM documents
WHERE user_id = $1
ORDER BY updated DESC
`

func (q *Queries) GetDocumentsByUserID(ctx context.Context, userID int32) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Private,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET content = $2, updated = now()
WHERE id = $1
RETURNING id, user_id, content, private, created, updated
`

type UpdateDocumentParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument, arg.ID, arg.Content)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Private,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
